### ISSUE TITLE
[Optimism] Could not convert receipt to elixir

### ISSUE THREAD

**Issue by zillnet-l2** [blockscout/blockscout#10123]
### Description

blockscout-backend: v6.6.0-beta
op-geth: v1.101315.1

```
** (ArgumentError) Could not convert receipt to elixir
...
Errors:
  {:unknown_key, %{key: "l1BlobBaseFeeScalar", value: "0x0"}}
  {:unknown_key, %{key: "l1BlobBaseFee", value: "0x45"}}
  {:unknown_key, %{key: "l1BaseFeeScalar", value: "0xf4240"}}

    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/receipt.ex:303: EthereumJSONRPC.Receipt.ok!/2
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 6.6.0) lib/ethereum_jsonrpc/receipts.ex:148: EthereumJSONRPC.Receipts.fetch/2
    (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.2) proc_lib.erl:240::proc_lib.init_p_do_apply/3
```

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

op-geth

### Type of the chain

L2

### Steps to reproduce

Upgrade op-geth to v1.101315.1, and the blockscout-backend indexer reports an error when importing the block if the receipt of the tx in the block contains the following fields:
l1BlobBaseFeeScalar
l1BlobBaseFee
l1BaseFeeScalar

These three fields were added in op-geth v1.101315.1

### Backend version

v6.6.0-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.0 Erlang/OTP 25 [erts-13.1.5]

### Operating system

Linux

### Additional information

To temporarily solve the problem, modify this file：
apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex:385
From
```
defp entry_to_elixir({key, _}) when key in ~w(depositNonce depositReceiptVersion) do
```
To
```
defp entry_to_elixir({key, _}) when key in ~w(depositNonce depositReceiptVersion l1BlobBaseFeeScalar l1BlobBaseFee l1BaseFeeScalar) do
```

**Comment by vbaranov** [comment]
@zillnet-l2 you should use `blockscout/blockscout-optimism:latest` docker image as a backend.

**Comment by zillnet-l2** [comment]
@vbaranov 
Thank you for your prompt response.

If I choose not to use Docker and instead compile from source, should I use the `production-optimism` branch of the `blockscout/blockscout` repository?

Thank you for your assistance.

**Comment by vbaranov** [comment]
You should use `master` branch of the repository, but set `CHAIN_TYPE=optimism` at the compilation time.

**Comment by zillnet-l2** [comment]
Thank you for your response. 

I am indeed using the master branch of the repository and have set CHAIN_TYPE=optimism during compilation.

I am confident that the issue lies within the code, not the configuration. Could you please provide further assistance?

**Comment by vbaranov** [comment]
> Thank you for your response.
> 
> I am indeed using the master branch of the repository and have set CHAIN_TYPE=optimism during compilation.
> 
> I am confident that the issue lies within the code, not the configuration. Could you please provide further assistance?

Could you please pull updates from `master` branch? This should be fixed.

**Comment by zillnet-l2** [comment]
I have already pulled updates from the master branch, then searched the entire repository using the keywords l1BlobBaseFeeScalar/l1BlobBaseFee/l1BaseFeeScalar, but the search results were empty.

I read the code in the file apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex, and it does not handle those three fields.

I'm sure it's not fixed.

**Comment by vbaranov** [comment]
@zillnet-l2 

https://github.com/blockscout/blockscout/blob/dc44b18030ba9babb47286abce2c7966af4c10f1/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex#L373

**Comment by zillnet-l2** [comment]
Sorry, my mistake. I was so dizzy from writing code that I didn't successfully execute the git pull. I am very, very sorry.
