### ISSUE TITLE
Gnosis Chain: Smart contract showing as EOA

### ISSUE THREAD

**Issue by fnanni-0** [blockscout/blockscout#5751]
[This](https://blockscout.com/xdai/mainnet/address/0x48CcA4b7E5e1C38353295966F6c6B1B1D462B775) is a contract created from this [contract factory](https://blockscout.com/xdai/mainnet/address/0x67d3673CF19a6b0Ad70D76b4e9C6f715177eb48b). However, it shows as EOA.

**Comment by vbaranov** [comment]
@fnanni-0 probably, you're aware in which transaction it was created? If yes, could you please share hash of the transaction?

**Comment by fnanni-0** [comment]
https://blockscout.com/xdai/mainnet/tx/0xd70d31383b215a23e3a0dbc989f4cefec5ed84887cfd65207f730e5d06f8e624

**Comment by julien51** [comment]
We have the same issue with this contract: https://blockscout.com/poa/xdai/address/0x24d25a15b156225E56cd0AD8FfEFE208a4fb6fE8/transactions#address-tabs

It was created from this transaction: https://blockscout.com/xdai/mainnet/tx/0x013363252b2535f8a524be3acaa6a52cd157ddeb3e8d8e4d76eab5023ba9eb67

please let us know if we can help debug this in anyway... :)

**Comment by vbaranov** [comment]
@julien51 @fnanni-0 There was an issue with archive node - resolved by replacing full archive node endpoint. Missing contracts codes have been fetched by Blockscout. There should be no more EOA which are actually smart-contracts.

**Comment by fnanni-0** [comment]
Thanks @vbaranov! One more thing, the contract is a minimal proxy deployed using https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol. How can I make Blockscout recognize that it is a proxy contract?

**Comment by vbaranov** [comment]
@fnanni-0 you don't need attempt extra steps. Blockscout already recongnizes the contract as a minimal proxy contract https://blockscout.com/xdai/mainnet/address/0x48CcA4b7E5e1C38353295966F6c6B1B1D462B775/contracts#address-tabs

<img width="528" alt="Screenshot 2022-07-27 at 16 52 36" src="https://user-images.githubusercontent.com/4341812/181264379-49c30c55-ca38-41f1-96cb-009d34927615.png">

**Comment by fnanni-0** [comment]
@vbaranov this still happens with some contracts. For example:

https://blockscout.com/xdai/mainnet/address/0x599836608A3680Ed20c760Bb18A8AF764a362aA9
which was created at tx
https://blockscout.com/xdai/mainnet/tx/0x8d948494e2ff7658062f6b409f4fcfecc0fe6009b5a36950130260e2ada231b6

**Comment by vbaranov** [comment]
@fnanni-0 sorry about that, resolved.
