### ISSUE TITLE
Deploy blockscout Fail!!

### ISSUE THREAD

**Issue by TW001ChenYI** [blockscout/blockscout#5855]
*Describe your issue here.*

I followed the instructions on the official website and got the following problem.

Is there an error in the environment settings?

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 12
* Operating System:VMware Ubuntu 18.04
* Blockscout Version/branch: v4.1.5-beta

### Steps to reproduce
1. git clone https://github.com/blockscout/blockscout.git
2. cd blockscout/docke
3. sudo COIN=ETH \
SUBNETWORK=Quickstart \
CHAIN_ID=22222 \
ETHEREUM_JSONRPC_VARIANT=geth \
ETHEREUM_JSONRPC_TRANSPORT=http \
ETHEREUM_JSONRPC_HTTP_URL=http://x.x.x.x:9998 \
ETHEREUM_JSONRPC_WS_URL=ws://x.x.x.x:9999 \
make start

### Expected behaviour
![image](https://user-images.githubusercontent.com/86778581/183595993-483bd442-0dc5-41b2-a467-9da910aceafc.png)
### Actual behaviour

![image](https://user-images.githubusercontent.com/86778581/183596369-7fb2d632-e1be-4fa0-8042-ab82e49ac715.png)

**Comment by vbaranov** [comment]
@TW001ChenYI please add `PORT` env variable as well. For instance, `PORT=4000`

**Comment by TW001ChenYI** [comment]
@vbaranov 
`echo $PORT`
:4000

I tried it but the result is still the same

**Comment by TW001ChenYI** [comment]
This is my current env


export COIN="ETH"
export NETWORK="quorum"
export CHAIN_PORT=12345"
export DATABASE_URL="postgresql://postgres:@localhost:5432/blockscout?ssl=false"
export PORT=4000
export ETHEREUM_JSONRPC_TRANSPORT="http"
export ETHEREUM_JSONRPC_VARIANT="geth"
export ETHEREUM_JSONRPC_HTTP_URL="http://localhost:22000"
export ETHEREUM_JSONRPC_WS_URL="ws://localhost:22005"
export ETHEREUM_JSONRPC_TRACE_URL="http://localhost:22000"


I tried it but the result is still the same,thanks

**Comment by vbaranov** [comment]
Please try update from master branch. It should resolve the issue.

**Comment by TW001ChenYI** [comment]
@vbaranov Thanks,All the above issues have been resolved,But the following problems occur:

Can not parse block timestamp of quorum Raft private chain,invalid Unix time

How to solve?

**Comment by vbaranov** [comment]
@TW001ChenYI GoQuorum is not officially supported. If its implemetation is different from supported clients (https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache), you should fix it by yourself or open a separate issue. Since Blockscout is open-source, community probably can help.

**Comment by TW001ChenYI** [comment]
https://consensys.net/docs/goquorum/en/21.10.0/tutorials/quorum-dev-quickstart/using-the-quickstart/#blockscout

**Comment by rinor** [comment]
@TW001ChenYI you can try and change https://github.com/blockscout/blockscout/blob/7569dace3c81463de2232f91d8d6ebdfad29d524/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex#L472 to smth like 
```diff
diff --git a/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex b/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
index ab6399f93..e35270b09 100644
--- a/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
+++ b/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
@@ -469,7 +469,7 @@ defmodule EthereumJSONRPC do
         nil
 
       quantity ->
-        Timex.from_unix(quantity)
+        Timex.from_unix(String.to_integer(String.slice("#{quantity}", 0, 10)))
     end
   end
 ```
 and see if it moves along.

**Comment by TW001ChenYI** [comment]
@rinor I tried it but the result is still the same,thanks



Retrying.
2022-08-12T09:04:30.745 application=indexer fetcher=block_catchup first_block_number=2 last_block_number=0 missing_block_count=3 shrunk=false [info] Index had to catch up.
2022-08-12T09:04:30.745 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
2022-08-12T09:04:31.917 application=tzdata [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 11 Aug 2022 00:05:52 GMT.
2022-08-12T09:04:33.258 application=indexer fetcher=block_catchup first_block_number=2 last_block_number=0 [error] ** (ArgumentError) invalid Unix time 1660105952047879643
    (elixir 1.13.1) lib/calendar/datetime.ex:402: DateTime.from_unix!/3
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/block.ex:594: EthereumJSONRPC.Block.entry_to_elixir/1
    (elixir 1.13.1) lib/enum.ex:1597: anonymous fn/3 in Enum.map/2
    (stdlib 3.17) maps.erl:410: :maps.fold_1/3
    (elixir 1.13.1) lib/enum.ex:2408: Enum.map/2
    (elixir 1.13.1) lib/enum.ex:1496: Enum.into/3
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2

**Comment by Paty1283** [comment]
Ijvhib6bin
